// new specialist perks

::Const.Strings.PerkName.LegendSpecialistInventor <- "Inventor\'s Armaments";
::Const.Strings.PerkDescription.LegendSpecialistInventor <- "Using your wits and tools, you\'ve managed to create aids, which help you use unwieldy mechanical weapons with skill and dexterity.\n\n[color=#4f1800][u]Specialist Weapon Perk:[/u][/color]\n•Gain [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] Ranged Skill while using a Handgonne.\n\n• Reduce AP cost for reloads by [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] when taking [color=#993b00]Crossbow Mastery[/color].\n\n• Gain [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill while using a Firelance.\n\n• When taking [color=#008060]Spear Mastery[/color] you will also gain [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• For other weapons classified as Firearms you can get a scaling percentage of this bonus increasing by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] for each level after level 4, reaching a maximum bonus of [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] at level 15.";
::Const.Strings.PerkName.LegendSpecialistBodyguard <- "Schwertkampfer";
::Const.Strings.PerkDescription.LegendSpecialistBodyguard <- "Eating and sleeping with your blade has turned it into an extension of your arm.\n\n[color=#4f1800][u]Specialist Weapon Perk:[/u][/color]\n• Gain [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill, [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] damage penetration and [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] armor damage when using a Longsword.\n\n• When taking [color=#008060]Two Handed Sword Mastery[/color] gain [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] damage.\n\n• For other weapons classified as a Two-Handed Sword you get a scaling percentage of this bonus  increasing by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] with each level after level 4, reaching a maximum bonus of [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] at level 15.";
::Const.Strings.PerkName.LegendSpecialistInquisition <- "Trial for Witchcraft";
::Const.Strings.PerkDescription.LegendSpecialistInquisition <- "Nobody expects the Inquisition!\n\n[color=#4f1800][u]Specialist Weapon Perk:[/u][/color]\n•Gain [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] Ranged Skill while using Hand Crossbow or Spiked Impaler.\n\n• When taking [color=#008060]Crossbow Mastery[/color] gain [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] damage.\n\n• Gain [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee Damage while using a Wooden Stake.\n\n• For other weapons classified as Crossbows the bonus you can get a scaling percentage of this bonus increasing by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] for each level after level 4, reaching a maximum bonus of [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] at level 15.\n\n• While using Crossbows the bonus will be doubled against Hexe and Alps.";
::Const.Strings.PerkName.LegendSpecialistClub <- "Browbeater\'s Bludgeon";
::Const.Strings.PerkDescription.LegendSpecialistClub <- "Mastering the art of leaning against a wall with a big stick has it\'s benefits.\n\n[color=#4f1800][u]Specialist Weapon Perk:[/u][/color]\n•Gain [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill and [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] fatigue per hit while using a Wooden Stick or Blundgeon.\n\n• When taking [color=#008060]Mace Mastery[/color] gain [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] damage.\n\n• For other weapons classified as One-Handed Mace you get a scaling percentage of this the bonus increasing by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] with each level after level 4, reaching a maximum bonus of [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] at level 15.";

// new slinger perks
::Const.Strings.PerkName.LegendSlingerSpins <- "Slinger\'s Spins";
::Const.Strings.PerkDescription.LegendSlingerSpins <- "The old sling still has tricks up it\'s sleeve.\n\n[color=#4f1800][u]Passive:[/u][/color]\n• Gain the [color=#400080]Prepare Bullet[/color] ability, which will activate each time you Wait your turn while holding a Sling or Slingstaff. Increases damage done by [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] and the Range of attacks by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].\n\n• If you get hit you will lose this effect.\n\n[color=#4f1800][u]Passive:[/u][/color]\n• One Handed Slings now ignore shield bonuses. Allows you to launch bombs and flasks from your Staff Sling for greater range.";
::Const.Strings.PerkName.LegendBarrage <- "Barrage";
::Const.Strings.PerkDescription.LegendBarrage <- "Turn your sling into a hand-held trebuchet!\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain [color=" + this.Const.UI.Color.PositiveValue + "]+15-30[/color] damage while using a slingstaff at range (but increases the AP cost of Sling Heavy Stone by 1 and Fatigue cost by 4). One Handed Slings now have a 33% on a hit to the body and 100% on a hit to the head to inflict Daze, Baffle, Stagger or Debilitate on the target.\n\n• If any 3 of the previous effects are already on the target, the target will be stunned instead.";

// new staff perks
::Const.Strings.PerkName.LegendStaffBlock <- "Staff Block";
::Const.Strings.PerkDescription.LegendStaffBlock <- "Tae Bonk!\n\n[color=#4f1800][u]Active:[/u][/color]\n• Grants the [color=#400080]Staff Riposte[/color] ability which allows counterattack any opponent that misses you in melee.\n\n[color=#4f1800][u]Passive:[/u][/color]\n• Additionally, while wielding a staff, the defense malus due to being surrounded by opponents is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]3[/color].\n\n• If you have [color=#993b00]Underdog[/color] or [color=#993b00]Battleheart[/color], this perk will instead increase defenses by [color=" + this.Const.UI.Color.PositiveValue + "]5[/color].";

// new song perks
::Const.Strings.PerkName.LegendMinnesanger <- "Minnesänger";
::Const.Strings.PerkDescription.LegendMinnesanger <- "\'Step outside mine walls, wearing an expensive tunic. Thee sayeth thou art highborn, but I heareth thou art eunich.\'\n\n[color=#4f1800][u]Passive:[/u][/color]\n• Grants  [color=" + this.Const.UI.Color.PositiveValue + "]2[/color] Hitpoints or Fatigue bonus to [color=#400080]Song of Life[/color] and [color=#400080]War Chant[/color] effect, respectively.";
::Const.Strings.PerkName.LegendMinnesanger <- "Minnesänger";
::Const.Strings.PerkDescription.LegendMinnesanger <- "\'Step outside mine walls, wearing an expensive tunic. Thee sayeth thou art highborn, but I heareth thou art eunich.\'\n\n[color=#4f1800][u]Passive:[/u][/color]\n• Grants  [color=" + this.Const.UI.Color.PositiveValue + "]2[/color] Hitpoints or Fatigue bonus to [color=#400080]Song of Life[/color] and [color=#400080]War Chant[/color] effect, respectively.";
::Const.Strings.PerkName.LegendMeistersanger <- "Meistersänger";
::Const.Strings.PerkDescription.LegendMeistersanger <- "You have stepped up above playing shameful songs, ridiculing nobles and are a musician of some renown, whos fine melodies can whip any company into a battle frenzy.\n\n[color=#4f1800][u]Passive:[/u][/color]\n• Every time you use [color=#400080]Song of Life[/color] and [color=#400080]War Chant[/color], everyone affected will also receive the [color=#400080]Military March[/color] effect.\n\n• [color=#400080]Military March[/color] will provide a chance on each skill used to recover Action Points.";