::Const.Strings.PerkDescription.LegendSpecialistButcherSkill = "Your skill on the butcher\'s block seems to be easily translated to chopping limbs on the battlefield.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using Cleavers, but not Whips.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Cleaver Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using a Butcher\'s Cleaver and it's legendary variety you will receive the maximum bonus.\n\n For non-specialist weapons of the same class, the bonus will scale by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] for each level after level 1 with [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] of the bonus achieved at level 11.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistButcherSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistButcherSkill;
::Const.Strings.PerkDescription.LegendSpecialistHammerSkill = "Diligent practice with the hammer each day has proven to be equally good at crafting armor and it's dismantling.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+40%[/color] armor damage while using One Handed Hammer.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Hammer Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using a Blacksmith\'s Hammer and it's legendary variety you will receive the maximum bonus.\n\n For non-specialist weapons of the same class, the bonus will scale by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] for each level after level 1 with [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] of the bonus achieved at level 11.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistHammerSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistHammerSkill;
::Const.Strings.PerkDescription.LegendSpecialistKnifeSkill = "Life on the streets has shown you how to properly bury a knife in another person.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+40%[/color] armor penetration while using a Knife.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Dagger Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using Knife and Shiv and it's legendary variety you will receive the maximum bonus.\n\n For non-specialist weapons of the same class, the bonus will scale by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] for each level after level 1 with [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] of the bonus achieved at level 11.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistKnifeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistKnifeSkill;
::Const.Strings.PerkDescription.LegendSpecialistLuteSkill = "You\'ve understood that the instrument can both make a pretty coin in taverns, but also bash heads when the inevitable tavern brawl happens.\n\n[color=#4f1800][u]Passive:[/u][/color]\n• Gain [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee Skill and defense and damage while using a musical instrument. Deal an extra [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] when taking [color=" + this.Const.UI.Color.PositiveValue + "]Staff Mastery[/color].\n\nGain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+2[/color] fatigue per hit while using a One Handed Mace.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Mace Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage. \n\n• While using Musical Instrument and it's legendary variety you will receive the maximum bonus"
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistLuteSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistLuteSkill;
::Const.Strings.PerkDescription.LegendSpecialistMilitiaSkill = "You have mastered the trusty spear and you can use it to both dealing damage and keeping enemies at bay.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+6[/color] melee defense while using a Spear.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Spear Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using a Militia Spear, Ancient Spear or Wooden Spear you will receive the maximum bonus.\n\n For non-specialist weapons of the same class, the bonus will scale by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] for each level after level 1 with [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] of the bonus achieved at level 11.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistMilitiaSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistMilitiaSkill;
::Const.Strings.PerkDescription.LegendSpecialistPickaxeSkill = "Cracking rocks and cracking skulls aren\'t that much different.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using a Two Handed Hammer, Pickaxe or Military Pick.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Hammer Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using a Pickaxe or Military Pick you will receive the maximum bonus."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistPickaxeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPickaxeSkill;
::Const.Strings.PerkDescription.LegendSpecialistPitchforkSkill = "Years of using farming tools have given you an understanding of how to stab true and slash in smooth strokes.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] armor damage while using a Pitchfork, Wooden Pitchfork, Hoe, Scythe, Warscythe, Warfork or Wooden Flail.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Polearm Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using a Pitchfork, Wooden Pitchfork, Hoe, Scythe, Warscythe, Warfork or Wooden Flail you will receive the maximum bonus."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistPitchforkSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPitchforkSkill;
::Const.Strings.PerkDescription.LegendSpecialistShortbowSkill = "From small game to big bounties.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] armor penetration while using a Bow Item.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Bow Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using Shortbows you will receive the maximum bonus."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistShortbowSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShortbowSkill;
::Const.Strings.PerkDescription.LegendSpecialistShovelSkill = "You used to dig up graves, now you're digging graves.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using a Shovel or Two Handed Mace.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Mace Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using Shovels or their legendary variety you will receive the maximum bonus."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistShovelSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShovelSkill;
::Const.Strings.PerkDescription.LegendSpecialistWoodaxeSkill = "Timber!\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using an Axe.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Axe Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using Woodcutter\'s Axe or Handsaw you will receive the maximum bonus."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistWoodaxeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistWoodaxeSkill;
::Const.Strings.PerkDescription.LegendSpecialistSickleSkill = "Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] armor penetration while using a One Handed Sword. While using a Sickle or Notched Blade you will receive an innate [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] bonus.\n\n For non-specialist weapons of the same class, the bonus will scale by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] for each level after level 1 with [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] of the bonus achieved at level 11.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistSickleSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistSickleSkill;
::Const.Strings.PerkDescription.LegendSpecialistNinetailsSkill = "Practice in the arts of punishment makes the tips of the cattail to inflict horrible injuries with greater accuracy.\n\n• Gain up to [color=" + this.Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] Damage on a hit to the head and while using Flails or Whips.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Flail Mastery[/color] or [color=" + this.Const.UI.Color.PositiveValue + "]Cleaver Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]6-16[/color] bonus damage.\n\n• While using a Cat o\' Nine Tails you will receive the maximum bonus.\n\n• For non-specialist weapons of the same class, the bonus for Three Headed Flail and Berserker chain is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]+25%[/color]."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistNinetailsSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistNinetailsSkill;
::Const.Strings.PerkDescription.LegendSpecialistScytheSkill = "Practicing with the unwieldy scythe has taught you how to twist your torso to produce repeatable smooth strokes.\n\n[color=#4f1800][u]Passive:[/u][/color]\n•Gain [color=" + this.Const.UI.Color.PositiveValue + "]+15[/color] melee skill while using a Scythe or Warscythe.\n\n• When taking [color=" + this.Const.UI.Color.PositiveValue + "]Polearm Mastery[/color] or [color=" + this.Const.UI.Color.PositiveValue + "]Cleaver Mastery[/color] you will also gain up to [color=" + this.Const.UI.Color.PositiveValue + "]10-15[/color] bonus damage."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistScytheSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistScytheSkill;